# Generated by Django 4.2.1 on 2023-06-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_beats_cambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
